# This is a basic workflow to help you get started with Actions

name: Deploy to WordPress.org

# Controls when the workflow will run
on:
  # Triggers the workflow on push request events but only for the main branch
  push:
    tags:
      - '*'

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  deploy-plugin:
    name: Deploy Plugin
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@main
      - name: WordPress Plugin Deploy
        uses: 10up/action-wordpress-plugin-deploy@stable
        env:
          SVN_PASSWORD: ${{ secrets.SVN_PASSWORD }}
          SVN_USERNAME: ${{ secrets.SVN_USERNAME }}
          SLUG: search-attributes-for-woocommerce
          ASSETS_DIR: assets
